#!/bin/sh

DAEMON="qbittorrent"

case "$1" in
	start)
		printf 'Starting %s...\n' "$DAEMON"
		/usr/libexec/qbtos-control qbt-start
		;;
	stop)
		/usr/libexec/qbtos-control qbt-stop
		;;
	restart)
		"$0" stop
		"$0" start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
