#!/bin/sh

DAEMON="qbtos-watchdog"
PIDFILE="/var/run/$DAEMON.pid"

case "$1" in
	start)
		start-stop-daemon -S -q -b -m -p "$PIDFILE" \
			-x /usr/sbin/qbtos-watchdog
		;;
	stop)
		start-stop-daemon -K -q -p "$PIDFILE" || true
		rm -f "$PIDFILE"
		;;
	restart)
		"$0" stop
		"$0" start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
