table ip qbtos {
	set trusted_ipv4 {
		type ipv4_addr
		flags interval
		elements = { 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16 }
	}

	set wireguard_marks {
		type mark
	}

	chain input {
		type filter hook input priority filter; policy drop;
		iifname "lo" accept
		ct state established,related accept
		iifname "eth0" udp sport 67 udp dport 68 accept
		iifname "eth0" ip protocol icmp accept
		iifname "eth0" ip saddr @trusted_ipv4 tcp dport { 8080, 8081 } accept
		iifname { "wg0", "tun0" } tcp dport { 8080, 8081 } drop
		iifname { "wg0", "tun0" } accept
	}

	chain qbt_output {
		type filter hook output priority filter; policy accept;
		meta skuid "qbtos-qbt" oifname "lo" accept
		meta skuid "qbtos-qbt" oifname { "wg0", "tun0" } accept
		meta skuid "qbtos-qbt" oifname "eth0" meta mark @wireguard_marks meta l4proto udp accept
		meta skuid "qbtos-qbt" oifname "eth0" ip daddr @trusted_ipv4 tcp sport 8081 accept
		meta skuid "qbtos-qbt" reject
	}
}
