[system]
compatible=qbtos-rpi4
bootloader=uboot
boot-attempts=3
boot-attempts-primary=3
data-directory=/config/qbtos/rauc

[keyring]
path=/etc/rauc/keyring.pem
check-purpose=codesign

[slot.rootfs.0]
device=/dev/disk/by-partuuid/5142544f-02
type=raw
bootname=A

[slot.rootfs.1]
device=/dev/disk/by-partuuid/5142544f-03
type=raw
bootname=B
